import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, BarChart3, BookOpen, Check, ChevronRight, Menu, MessageCircle, Send, ShieldCheck, Sparkles, TrendingUp, Users, X } from "lucide-react";
import Logo from "../assets/Logo.png";

const LINKS = {
  telegram: "https://t.me/livefxeducation",
  whatsapp: "https://wa.me/qr/HCFRDG6CS63HG1",
  register: "https://trade.livefxm.com/register?referred_code=WZH06EOY",
};

const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55 } } };
const ExternalLink = ({ href, children, className = "" }) => <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>;

function MarketChart({ compact = false }) {
  return <div className={`relative mx-auto w-full overflow-hidden rounded-[2rem] border border-white/10 bg-[#0a1726] p-5 shadow-2xl shadow-cyan-950/40 sm:p-8 ${compact ? "max-w-md" : "max-w-[600px]"}`}>
    <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(rgba(139,211,255,.18) 1px, transparent 1px), linear-gradient(90deg, rgba(139,211,255,.18) 1px, transparent 1px)", backgroundSize: "25% 25%" }} />
    <div className="relative flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs uppercase tracking-[0.25em] text-cyan-300">FX / USD</p><p className="mt-1 text-2xl font-semibold text-white">1.0842 <span className="text-sm text-cyan-300">+1.24%</span></p></div><BarChart3 className="text-cyan-300" /></div>
    <svg viewBox="0 0 500 270" className="relative mt-6 h-64 w-full" role="img" aria-label="Rising market line"><defs><linearGradient id="line" x1="0" x2="1"><stop stopColor="#76e4ff" /><stop offset="1" stopColor="#3575ff" /></linearGradient><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#55d9ff" stopOpacity=".28" /><stop offset="1" stopColor="#55d9ff" stopOpacity="0" /></linearGradient></defs><path d="M0 222 C35 215 38 180 76 191 S120 136 153 157 S192 113 225 140 S262 99 296 112 S325 76 350 99 S389 38 420 64 S462 32 500 11 V270 H0Z" fill="url(#area)" /><path d="M0 222 C35 215 38 180 76 191 S120 136 153 157 S192 113 225 140 S262 99 296 112 S325 76 350 99 S389 38 420 64 S462 32 500 11" fill="none" stroke="url(#line)" strokeWidth="4" strokeLinecap="round" /><circle cx="500" cy="11" r="6" fill="#76e4ff" /></svg>
    <div className="relative flex justify-between text-[11px] text-slate-500"><span>09:00</span><span>12:00</span><span>15:00</span><span>18:00</span></div><div className="absolute bottom-5 left-5 flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-2 text-xs text-cyan-100 sm:bottom-8 sm:left-8"><span className="size-2 rounded-full bg-cyan-300" /> Live market view</div>
  </div>;
}

function CandleVisual() { return <div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#0a1726] p-6"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(139,211,255,.18) 1px, transparent 1px), linear-gradient(90deg, rgba(139,211,255,.18) 1px, transparent 1px)", backgroundSize: "20% 25%" }} /><div className="relative flex h-72 items-end justify-around gap-2 border-b border-white/10 pb-4">{[52, 90, 65, 120, 78, 145, 110, 175, 135, 215, 160, 230].map((h, i) => <div key={i} className="relative flex h-full items-end"><span className="absolute bottom-0 left-1/2 h-[calc(100%-8px)] w-px -translate-x-1/2 bg-cyan-200/60" style={{ height: `${h + 22}px` }} /><span className={`relative w-3 rounded-sm sm:w-5 ${i % 3 === 1 ? "bg-rose-300/80" : "bg-cyan-300/80"}`} style={{ height: `${h}px` }} /></div>)}</div><div className="relative mt-4 flex justify-between text-xs text-slate-500"><span>EUR/USD</span><span className="text-cyan-200">Momentum · 68.4</span></div></div>; }

function LandingPage() {
  const [open, setOpen] = useState(false);
  const nav = [{ label: "Why FXcelite", href: "#why" }, { label: "Markets", href: "#markets" }, { label: "Education", href: "#education" }, { label: "Community", href: "#community" }];
  const close = () => setOpen(false);
  const Section = ({ children, className = "" }) => <motion.section initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} variants={reveal} className={className}>{children}</motion.section>;
  return <main className="min-h-screen overflow-hidden bg-[#06111d] text-white selection:bg-cyan-300 selection:text-[#06111d]">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#06111d]/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="flex items-center" onClick={close}><img src={Logo} alt="FXcelite" className="h-12 w-auto origin-left scale-125 sm:h-14 sm:scale-150" /></a><div className="hidden items-center gap-7 md:flex">{nav.map((item) => <a key={item.href} href={item.href} className="text-sm text-slate-300 transition hover:text-cyan-200">{item.label}</a>)}<ExternalLink href={LINKS.register} className="rounded-full bg-cyan-300 px-5 py-3 text-sm font-bold text-[#06111d] transition hover:bg-white">Start Trading <ArrowRight className="ml-2 inline size-4" /></ExternalLink></div><button className="rounded-lg p-2 text-slate-200 md:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-white/10 bg-[#06111d] px-5 py-5 md:hidden"><div className="flex flex-col gap-5">{nav.map((item) => <a key={item.href} href={item.href} onClick={close} className="text-slate-200">{item.label}</a>)}<ExternalLink href={LINKS.register} className="rounded-full bg-cyan-300 px-5 py-3 text-center font-bold text-[#06111d]">Start Trading</ExternalLink></div></div>}</nav>

    <section id="top" className="relative mx-auto flex min-h-screen max-w-7xl items-center px-5 pb-16 pt-32 sm:px-8 lg:pt-28"><div className="absolute -right-40 top-20 size-[28rem] rounded-full bg-cyan-400/10 blur-3xl" /><div className="grid w-full items-center gap-14 lg:grid-cols-[1fr_.95fr] lg:gap-8"><motion.div initial="hidden" animate="visible" variants={reveal} className="relative z-10 max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-2 text-xs font-medium uppercase tracking-[0.2em] text-cyan-200"><Sparkles className="size-3.5" /> A sharper way to trade</div><h1 className="text-balance text-5xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-7xl">Make your next move with <span className="text-cyan-300">conviction.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-slate-300">FXcelite brings clear market access, practical tools, and a community that keeps you close to what matters.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ExternalLink href={LINKS.register} className="rounded-full bg-cyan-300 px-6 py-4 text-center font-bold text-[#06111d] transition hover:bg-white">Start Trading <ArrowRight className="ml-2 inline size-4" /></ExternalLink><ExternalLink href={LINKS.telegram} className="rounded-full border border-white/20 px-6 py-4 text-center font-semibold text-white transition hover:border-cyan-300 hover:text-cyan-200"><Send className="mr-2 inline size-4" /> Join Free Telegram</ExternalLink></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-400"><span><ShieldCheck className="mr-2 inline size-4 text-cyan-300" />Secure by design</span><span><TrendingUp className="mr-2 inline size-4 text-cyan-300" />Built for momentum</span></div></motion.div><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1, transition: { duration: .7, delay: .15 } }}><MarketChart /></motion.div></div></section>

    <Section id="why" className="border-y border-white/10 bg-[#091827] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">The FXcelite difference</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Less noise.<br /><span className="text-slate-400">More focus.</span></h2></div><div className="grid gap-8 sm:grid-cols-3">{[[Users,"A real community","Learn alongside people who take the craft seriously."],[TrendingUp,"Market perspective","Find context before you find your entry."],[ShieldCheck,"Clear conditions","Know your platform, tools, and next step."]].map(([Icon,title,body]) => <div key={title}><Icon className="mb-5 text-cyan-300" /><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></div></div></Section>

    <section id="markets" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">One platform, many possibilities</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Stay close to the markets that move you.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-slate-400">Explore forex, indices, commodities, and crypto from one considered trading experience.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{["Forex","Indices","Commodities","Crypto"].map((name) => <div key={name} className="rounded-2xl border border-white/10 bg-white/[.03] p-4 text-sm text-slate-200"><div className="mb-4 h-8 w-12 rounded bg-cyan-300/10" />{name}</div>)}</div></div><MarketChart compact /></div></section>

    <Section className="bg-[#091827] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Market insights</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Stay connected with the market.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-400">Watch the shape of momentum, understand the rhythm, and keep your decisions grounded in context.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-4 py-2 text-xs text-cyan-100">Momentum 68.4</span><span className="rounded-full border border-white/10 px-4 py-2 text-xs text-slate-300">Volatility normal</span></div></div><CandleVisual /></div></div></Section>

    <Section id="education" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="max-w-2xl"><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Trading education</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Learn before you trade.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Build your market vocabulary and approach each decision with a stronger foundation.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[BookOpen,"Market Basics","Build a clear starting point."],[BarChart3,"Technical Analysis","Read movement with purpose."],[Sparkles,"Trading Concepts","Turn ideas into a process."],[TrendingUp,"Market Understanding","Connect the signals." ]].map(([Icon,title,body]) => <div key={title} className="group rounded-3xl border border-white/10 bg-[#091827] p-6 transition hover:-translate-y-1 hover:border-cyan-300/40"><Icon className="text-cyan-300 transition group-hover:scale-110" /><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{body}</p><ChevronRight className="mt-6 text-cyan-300" /></div>)}</div></Section>

    <Section id="community" className="border-y border-white/10 bg-[#091827] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Community</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Join the trading community.</h2></div><p className="max-w-sm text-slate-400">Stay close to conversations that make the market feel less distant.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2"><ExternalLink href={LINKS.telegram} className="group rounded-[2rem] border border-cyan-300/40 bg-cyan-300 p-8 text-[#06111d] transition hover:-translate-y-1"><Send /><h3 className="mt-16 text-3xl font-semibold">Telegram</h3><p className="mt-3 opacity-70">Join Free Telegram Channel</p><ArrowRight className="mt-8 transition group-hover:translate-x-2" /></ExternalLink><ExternalLink href={LINKS.whatsapp} className="group rounded-[2rem] border border-white/10 bg-[#0c2133] p-8 transition hover:-translate-y-1 hover:border-cyan-300/40"><MessageCircle className="text-cyan-300" /><h3 className="mt-16 text-3xl font-semibold">WhatsApp</h3><p className="mt-3 text-slate-400">Join on WhatsApp</p><ArrowRight className="mt-8 text-cyan-300 transition group-hover:translate-x-2" /></ExternalLink></div></div></Section>

    <Section id="steps" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">How it works</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">A clearer path forward.</h2></div><div className="relative mt-16 grid gap-10 md:grid-cols-3 md:gap-0">{[["01","Learn","Understand the market."],["02","Connect","Join the trading community."],["03","Trade","Create your account and take the next step."]].map(([n,title,body],i) => <div key={n} className="relative border-t border-white/20 px-0 pt-5 md:px-8 md:first:pl-0 md:last:pr-0"><span className="text-sm text-cyan-300">{n}</span><h3 className="mt-10 text-2xl font-semibold">{title}</h3><p className="mt-3 max-w-xs leading-7 text-slate-400">{body}</p>{i < 2 && <ArrowRight className="absolute right-5 top-5 hidden text-cyan-300 md:block" />}</div>)}</div></Section>

    <Section className="bg-[#091827] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Built around the market</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Visual clarity for every move.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-400">From the first glance to the final decision, keep the important details in view.</p><ul className="mt-8 flex flex-col gap-4 text-sm text-slate-300">{["Focused market snapshots","Flexible access across devices","A view that keeps pace"].map((item) => <li key={item}><Check className="mr-3 inline text-cyan-300" />{item}</li>)}</ul></div><MarketChart /></div></div></Section>

    <Section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Why join</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">More than a place to trade.</h2></div><div className="grid gap-4 sm:grid-cols-2">{["Trading education","Market discussions","Community access","Market insights","Easy access","Trading opportunities"].map((item,i) => <div key={item} className="flex items-center gap-4 border-b border-white/10 py-5 text-lg text-slate-200"><span className="text-sm text-cyan-300">0{i+1}</span>{item}<ArrowRight className="ml-auto size-4 text-slate-500" /></div>)}</div></div></Section>

    <Section className="mx-5 mb-24 overflow-hidden rounded-[2rem] bg-cyan-300 px-6 py-16 text-center text-[#06111d] sm:mx-8 sm:px-10"><h2 className="mx-auto max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Take the next step.</h2><p className="mx-auto mt-5 max-w-xl text-lg opacity-75">Choose the channel that fits your journey and stay close to the market.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><ExternalLink href={LINKS.telegram} className="rounded-full bg-[#06111d] px-6 py-4 font-bold text-white transition hover:bg-white hover:text-[#06111d]">Join Free Telegram</ExternalLink><ExternalLink href={LINKS.whatsapp} className="rounded-full border border-[#06111d]/20 px-6 py-4 font-semibold transition hover:bg-white/40">Join on WhatsApp</ExternalLink><ExternalLink href={LINKS.register} className="rounded-full border border-[#06111d]/20 px-6 py-4 font-semibold transition hover:bg-white/40">Start Trading</ExternalLink></div></Section>

    <section className="mx-5 mb-8 overflow-hidden rounded-[2rem] border border-white/10 bg-[#0c2133] px-6 py-20 text-center sm:mx-8 sm:px-10"><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Your next chapter</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Ready to start trading?</h2><p className="mx-auto mt-5 max-w-xl text-lg text-slate-400">Make your next move with a community and platform built to keep you focused.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><ExternalLink href={LINKS.register} className="rounded-full bg-cyan-300 px-6 py-4 font-bold text-[#06111d] transition hover:bg-white">Start Trading <ArrowRight className="ml-2 inline size-4" /></ExternalLink><ExternalLink href={LINKS.telegram} className="rounded-full border border-white/20 px-6 py-4 font-semibold transition hover:border-cyan-300">Telegram</ExternalLink><ExternalLink href={LINKS.whatsapp} className="rounded-full border border-white/20 px-6 py-4 font-semibold transition hover:border-cyan-300">WhatsApp</ExternalLink></div></section>

    <footer className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><div className="grid gap-10 border-b border-white/10 pb-12 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><a href="#top"><img src={Logo} alt="FXcelite" className="h-12 w-auto" /></a><p className="mt-5 max-w-xs text-sm leading-6 text-slate-500">Clear market access, practical tools, and a community for your next move.</p></div><div><h3 className="text-sm font-semibold text-white">Community</h3><div className="mt-5 flex flex-col gap-3 text-sm text-slate-400"><ExternalLink href={LINKS.telegram}>Telegram</ExternalLink><ExternalLink href={LINKS.whatsapp}>WhatsApp</ExternalLink></div></div><div><h3 className="text-sm font-semibold text-white">Trading</h3><div className="mt-5 flex flex-col gap-3 text-sm text-slate-400"><ExternalLink href={LINKS.register}>Start Trading</ExternalLink><ExternalLink href={LINKS.register}>Register</ExternalLink></div></div><div><h3 className="text-sm font-semibold text-white">Quick links</h3><div className="mt-5 flex flex-col gap-3 text-sm text-slate-400"><a href="#top">Home</a><a href="#community">Community</a><a href="#education">Education</a><a href="#markets">Trading</a><a href="#community">Join Us</a></div></div></div><div className="flex flex-col gap-3 pt-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} FXcelite. All rights reserved.</span><span>Trading involves risk. Terms and conditions apply.</span></div></footer>
  </main>;
}

export default LandingPage;
